"""Dream log: a human-readable report of each dream cycle."""

import logging
import os
from datetime import datetime

from config import DREAM_LOG_DIR

log = logging.getLogger("hermesyume.log")

LABELS = {"memory": "MEMORY.md (agent notes)", "user": "USER.md (user profile)"}


def _q(text: str, n: int = 160) -> str:
    text = text.replace("\n", " ").replace("`", "'")
    return f"`{text[:n]}{'...' if len(text) > n else ''}`"


def write_dream_log(nrem: dict, rem: dict, dry_run: bool = False) -> str:
    os.makedirs(DREAM_LOG_DIR, exist_ok=True)
    now = datetime.now().astimezone()
    suffix = "_dry-run" if dry_run else ""
    filepath = os.path.join(DREAM_LOG_DIR, now.strftime("%Y-%m-%d_%H%M") + suffix + ".md")

    lines = [
        f"# Dream Log -- {now.strftime('%Y-%m-%d %H:%M %Z')}" + (" (dry run)" if dry_run else ""),
        "",
        "## NREM (sessions -> facts)",
        "",
        f"- Sessions replayed: {nrem.get('sessions', 0)}",
        f"- Extra episode files: {len(nrem.get('episode_files', []))}",
        f"- Chunks: {nrem.get('chunks', 0)}",
        f"- Clusters: {nrem.get('clusters', 0)}",
        f"- **New facts: {len(nrem.get('facts', []))}**",
        f"- Already known (reinforced): {nrem.get('skipped_dup', 0)}",
        "",
    ]
    for f in nrem.get("facts", []):
        lines.append(f"- [{f['target']}] ({f.get('importance', 0.5):.2f}) {_q(f['text'])}")
    if nrem.get("facts"):
        lines.append("")

    for target, r in rem.get("targets", {}).items():
        pct = 100 * r["after_chars"] / r["limit"] if r["limit"] else 0
        lines += [
            f"## REM -- {LABELS.get(target, target)}",
            "",
            f"- Size: {r['before_chars']} -> **{r['after_chars']}** chars "
            f"({pct:.0f}% of {r['limit']}, budget {r['budget']})",
            f"- Entries: {r['entries_before']} -> {r['entries_after']}",
            f"- Added: {len(r['added'])} / Merged: {len(r['merged'])} / "
            f"Consolidated: {len(r['consolidated'])} / Shortened: {len(r['shortened'])} / "
            f"Forgotten: {len(r['forgotten'])} / Reinforced: {r['reinforced']}",
            "",
        ]
        if r["added"]:
            lines += ["### Added", ""] + [f"- {_q(t)}" for t in r["added"]] + [""]
        if r["merged"]:
            lines += ["### Merged (state changes)", ""]
            for m in r["merged"]:
                lines += [f"- {_q(b, 100)}" for b in m["before"]]
                lines += [f"  -> {_q(m['after'])}", ""]
        if r["consolidated"]:
            lines += ["### Consolidated (different aspects)", ""]
            for c in r["consolidated"]:
                lines += [f"- {_q(b, 100)}" for b in c["before"]]
                lines += [f"  -> {_q(a)}" for a in c["after"]] + [""]
        if r["shortened"]:
            lines += ["### Shortened", ""]
            for s in r["shortened"]:
                lines += [f"- {_q(s['before'], 100)}", f"  -> {_q(s['after'])}"]
            lines.append("")
        if r["forgotten"]:
            lines += ["### Forgotten (archived in memory-archive/forgotten.jsonl)", ""]
            lines += [f"- ({x['score']:.2f}, {x['reason']}) {_q(x['text'])}" for x in r["forgotten"]]
            lines.append("")
        if r["blocked"]:
            lines += ["### Blocked", ""]
            lines += [f"- ({x['reason']}) {_q(x['text'])}" for x in r["blocked"]]
            lines.append("")
        if r["ops_skipped"]:
            lines += ["### Skipped at write time", ""]
            for op in r["ops_skipped"]:
                what = op.get("text") or op.get("old", "")
                lines.append(f"- {op['op']} ({op['reason']}): {_q(what, 100)}")
            lines.append("")

    lines += ["---", f"*Generated by HermesYume at {now.isoformat()}*", ""]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    log.info("Dream log written: %s", filepath)
    return filepath
